### Brain-hacking 101

Author: [**Ariel Rokem**](http://arokem.org), [**The University of Washington eScience Institute**](http://escience.washington.edu)

### Hack 1: Read your data into an array

When you conduct a neuroimaging experiment, the computer that controls the scanner and receives the data from the scanner saves your data to a file. Neuroimaging data appears in many different file formats: `NiFTI`, `Minc`, `Dicom`, etc. These files all contain representations of the data that you collected in the form of an **array**. 

What is an array? It is a way of representing the data in the computer memory as a *table*, that is *multi-dimensional* and *homogenous*.

What does this mean? 

- *table* means that you will be able to read all or some of the numbers representing your data by addressing the variable that holds your array. It's like addressing a member of your lab to tell you the answer to a question you have, except here you are going to 'ask' a variable in your computer memory. Arrays are usually not as smart as your lab members, but they have very good memory.

- *multi-dimensional* means that you can represent different aspects of your data along different axes. For example, the three dimensions of space can be represented in different dimensions of the table:

![Arrays](./images/array.svg)

- *homogenous* actually means two different things: 
    - The shape of the array is homogenous, so if there are three items in the first column, there have to be three items in all the columns. 
    - The data-type is homogenous. If the first item is an integer, all the other items will be integers as well.

To demonstrate the properties of arrays, we will use the [`numpy`](https://numpy.org) library. This library contains implementations of many scientifically useful functions and objects. In particular, it contains an implementation of arrays that we will use throughout the folllowing examples.

In [13]:
import numpy as np

In [14]:
# Numpy is a package. To see what's in a package, type the name, a period, then hit tab
#np?
#np.

In [15]:
# Some examples of numpy functions and "things":
print(np.sqrt(4))
print(np.pi)  # Not a function, just a variable
print(np.sin(np.pi)) # A function on a variable :) 

2.0
3.14159265359
1.22464679915e-16


### Numpy arrays (ndarrays)

Creating a NumPy array is as simple as passing a sequence to `np.array` 

In [16]:
arr1 = np.array([1, 2.3, 4])   
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)


<type 'numpy.ndarray'>
float64
(3,)


In [17]:
print(arr1)

[ 1.   2.3  4. ]


### You can create arrays with special generating functions: 

`np.arange(start, stop, [step])`

`np.zeros(shape)`

`np.ones(shape)`

In [18]:
arr4 = np.arange(2, 5)
print(arr4)
arr5 = np.arange(1, 5, 2)
print(arr5)
arr6 = np.arange(1, 10, 2)
print(arr6)

[2 3 4]
[1 3]
[1 3 5 7 9]


In [19]:
arr4 = np.arange(2, 5)
print(arr4)
arr5 = np.arange(1, 5, 2)
print(arr5)
arr6 = np.arange(1, 10, 2)
print(arr6)

[2 3 4]
[1 3]
[1 3 5 7 9]


## Exercise : Create an Array

Create an array with values ranging from 0 to 10, in increments of 0.5.

Reminder: get help by typing np.arange?, np.ndarray?, np.array?, etc.

### Arithmetic with arrays

Since numpy exists to perform efficient numerical operations in Python, arrays have all the usual arithmetic operations available to them. These operations are performed element-wise (i.e. the same operation is performed independently on each element of the array).

In [20]:
A = np.arange(5)
B = np.arange(5, 10)

print (A+B)

print(B-A)

print(A*B)

[ 5  7  9 11 13]
[5 5 5 5 5]
[ 0  6 14 24 36]


### What would happen if A and B did not have the same `shape`?

### Arithmetic with scalars:

In addition, if one of the arguments is a scalar, that value will be applied to all the elements of the array.

In [21]:
A = np.arange(5)
print(A+10)
print(2*A)
print(A**2)

[10 11 12 13 14]
[0 2 4 6 8]
[ 0  1  4  9 16]


### Arrays are addressed through indexing

**Python uses zero-based indexing**: The first item in the array is item `0`

The second item is item `1`, the third is item `2`, etc.

In [25]:
print(A)
print(A[0])
print(A[1])
print(A[2])

[0 1 2 3 4]
0
1
2


### Data in nifti files is stored as an array 

We can read out this array into the computer memory using the `nibabel` library

In [26]:
import nibabel as nib

In [28]:
img = nib.load('./data/run1.nii.gz')

In [29]:
data = img.get_data()

In [30]:
data.shape

(64, 64, 30, 191)